{
    'name': "Cybill Send SMS",
    'version': '0.1',
    'author': "Cybill Technologies",
    'category': 'Tools',
    'summary':'You can use multiple gateway for multiple sms template to send SMS.',
    'description':'Allows you to send SMS to the mobile no.',
    'website': "http://www.cybilltechsolutions.com/",
    'depends': ['base','web','point_of_sale'],
    'data': [
        'view/send_sms_view.xml',
        'view/ir_actions_server_views.xml',
        'view/sms_track_view.xml',
        'view/gateway_setup_view.xml',
        'wizard/sms_compose_view.xml',
        'security/ir.model.access.csv',
    ],
    'images':[],
    'license': 'LGPL-3',
    'installable':True,
    'auto_install':False,
}
